//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiaPortalToolbox.Doc.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TiaPortalToolbox.Doc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Author.
        /// </summary>
        public static string AuthorParagraph {
            get {
                return ResourceManager.GetString("AuthorParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Block interface.
        /// </summary>
        public static string BlockInterfaceParagraph {
            get {
                return ResourceManager.GetString("BlockInterfaceParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change description.
        /// </summary>
        public static string ChangeDescriptionColumn {
            get {
                return ResourceManager.GetString("ChangeDescriptionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change log.
        /// </summary>
        public static string ChangeLogHeader {
            get {
                return ResourceManager.GetString("ChangeLogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Constant identifier, values and description.
        /// </summary>
        public static string ConstantText {
            get {
                return ResourceManager.GetString("ConstantText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data type.
        /// </summary>
        public static string DatatypeColumn {
            get {
                return ResourceManager.GetString("DatatypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PLC data types.
        /// </summary>
        public static string DatatypeHeader {
            get {
                return ResourceManager.GetString("DatatypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default value.
        /// </summary>
        public static string DefaultvalueColumn {
            get {
                return ResourceManager.GetString("DefaultvalueColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string DescriptionColumn {
            get {
                return ResourceManager.GetString("DescriptionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status &amp; Error codes.
        /// </summary>
        public static string ErrorCodeText {
            get {
                return ResourceManager.GetString("ErrorCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Functional description.
        /// </summary>
        public static string FonctionalDescriptionParagraph {
            get {
                return ResourceManager.GetString("FonctionalDescriptionParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifier.
        /// </summary>
        public static string IdentifierColumn {
            get {
                return ResourceManager.GetString("IdentifierColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In/Out parameter.
        /// </summary>
        public static string InOutParameterParagraph {
            get {
                return ResourceManager.GetString("InOutParameterParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Input parameter.
        /// </summary>
        public static string InputParameterParagraph {
            get {
                return ResourceManager.GetString("InputParameterParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Interface description.
        /// </summary>
        public static string InterfaceDescriptionParagraph {
            get {
                return ResourceManager.GetString("InterfaceDescriptionParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Output parameter.
        /// </summary>
        public static string OutputParameterParagraph {
            get {
                return ResourceManager.GetString("OutputParameterParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parameter description.
        /// </summary>
        public static string ParameterDescriptionParagraph {
            get {
                return ResourceManager.GetString("ParameterDescriptionParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Program blocks.
        /// </summary>
        public static string ProgramBlockHeader {
            get {
                return ResourceManager.GetString("ProgramBlockHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Short description.
        /// </summary>
        public static string ShortDescriptionParagraph {
            get {
                return ResourceManager.GetString("ShortDescriptionParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statics parameter.
        /// </summary>
        public static string StaticsParameterParagraph {
            get {
                return ResourceManager.GetString("StaticsParameterParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PLC tags &amp; constants.
        /// </summary>
        public static string TagsConstantsHeader {
            get {
                return ResourceManager.GetString("TagsConstantsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User defined datatype(s).
        /// </summary>
        public static string UdtParagraph {
            get {
                return ResourceManager.GetString("UdtParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version &amp; Date.
        /// </summary>
        public static string VersionColumn {
            get {
                return ResourceManager.GetString("VersionColumn", resourceCulture);
            }
        }
    }
}
