//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiaPortalToolbox.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TiaPortalToolbox.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TIA Portal toolbox.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Author.
        /// </summary>
        public static string DocumentPageAuthorColumnHeader {
            get {
                return ResourceManager.GetString("DocumentPageAuthorColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Author: .
        /// </summary>
        public static string DocumentPageAuthorText {
            get {
                return ResourceManager.GetString("DocumentPageAuthorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default value.
        /// </summary>
        public static string DocumentPageDefaultValueColumnHeader {
            get {
                return ResourceManager.GetString("DocumentPageDefaultValueColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string DocumentPageDescriptionColumnHeader {
            get {
                return ResourceManager.GetString("DocumentPageDescriptionColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edited.
        /// </summary>
        public static string DocumentPageEditedColumnHeader {
            get {
                return ResourceManager.GetString("DocumentPageEditedColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Family: .
        /// </summary>
        public static string DocumentPageFamilyText {
            get {
                return ResourceManager.GetString("DocumentPageFamilyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Interface.
        /// </summary>
        public static string DocumentPageInterfaceExpandeHeader {
            get {
                return ResourceManager.GetString("DocumentPageInterfaceExpandeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Library: .
        /// </summary>
        public static string DocumentPageLibraryText {
            get {
                return ResourceManager.GetString("DocumentPageLibraryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading PLC blocks.
        /// </summary>
        public static string DocumentPageLoadTitle {
            get {
                return ResourceManager.GetString("DocumentPageLoadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log.
        /// </summary>
        public static string DocumentPageLogExpandeHeader {
            get {
                return ResourceManager.GetString("DocumentPageLogExpandeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The document has been created successfully.
        /// </summary>
        public static string DocumentPageMessageBuildedText {
            get {
                return ResourceManager.GetString("DocumentPageMessageBuildedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Document created.
        /// </summary>
        public static string DocumentPageMessageBuildedTitle {
            get {
                return ResourceManager.GetString("DocumentPageMessageBuildedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Document settings are not configured.
        /// </summary>
        public static string DocumentPageMessageErrorSettingsText {
            get {
                return ResourceManager.GetString("DocumentPageMessageErrorSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Setting error.
        /// </summary>
        public static string DocumentPageMessageErrorTitle {
            get {
                return ResourceManager.GetString("DocumentPageMessageErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string DocumentPageNameColumnHeader {
            get {
                return ResourceManager.GetString("DocumentPageNameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Build document.
        /// </summary>
        public static string DocumentPageRibbonTabBuildDocumentHeader {
            get {
                return ResourceManager.GetString("DocumentPageRibbonTabBuildDocumentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Documents.
        /// </summary>
        public static string DocumentPageRibbonTabHeader {
            get {
                return ResourceManager.GetString("DocumentPageRibbonTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        public static string DocumentPageTypeColumnHeader {
            get {
                return ResourceManager.GetString("DocumentPageTypeColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version.
        /// </summary>
        public static string DocumentPageVersionColumnHeader {
            get {
                return ResourceManager.GetString("DocumentPageVersionColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Documents.
        /// </summary>
        public static string MainPageDocumentTitle {
            get {
                return ResourceManager.GetString("MainPageDocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HMI Alarms.
        /// </summary>
        public static string MainPageHmiAlarmTitle {
            get {
                return ResourceManager.GetString("MainPageHmiAlarmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open exist project.
        /// </summary>
        public static string NoProjectPageOpenTitle {
            get {
                return ResourceManager.GetString("NoProjectPageOpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select projet openned.
        /// </summary>
        public static string NoProjectPageSelectTitle {
            get {
                return ResourceManager.GetString("NoProjectPageSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open exist project.
        /// </summary>
        public static string OpenProjectDialogTitle {
            get {
                return ResourceManager.GetString("OpenProjectDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connect to TIA Portal.
        /// </summary>
        public static string OpenProjectProgressDialogAttaching {
            get {
                return ResourceManager.GetString("OpenProjectProgressDialogAttaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open TIA Portal.
        /// </summary>
        public static string OpenProjectProgressDialogStarting {
            get {
                return ResourceManager.GetString("OpenProjectProgressDialogStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open TIA Portal project.
        /// </summary>
        public static string OpenProjectProgressDialogTitle {
            get {
                return ResourceManager.GetString("OpenProjectProgressDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm.
        /// </summary>
        public static string PreSelectionAssemblyConfirmText {
            get {
                return ResourceManager.GetString("PreSelectionAssemblyConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do not show window again.
        /// </summary>
        public static string PreSelectionAssemblyHideDialogText {
            get {
                return ResourceManager.GetString("PreSelectionAssemblyHideDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Openness version.
        /// </summary>
        public static string PreSelectionAssemblyOpennessVersionText {
            get {
                return ResourceManager.GetString("PreSelectionAssemblyOpennessVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TIA Portal version.
        /// </summary>
        public static string PreSelectionAssemblyTiaPortalVersionText {
            get {
                return ResourceManager.GetString("PreSelectionAssemblyTiaPortalVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pre selection assembly versions.
        /// </summary>
        public static string PreSelectionAssemblyTitle {
            get {
                return ResourceManager.GetString("PreSelectionAssemblyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export of the PLC block.
        /// </summary>
        public static string ProgressDialogExportHeader {
            get {
                return ResourceManager.GetString("ProgressDialogExportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attach.
        /// </summary>
        public static string SelectProjectDialogAttachButtonText {
            get {
                return ResourceManager.GetString("SelectProjectDialogAttachButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string SelectProjectDialogCancelButtonText {
            get {
                return ResourceManager.GetString("SelectProjectDialogCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select project.
        /// </summary>
        public static string SelectProjectDialogTitle {
            get {
                return ResourceManager.GetString("SelectProjectDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings page placeholder text.  Your app description goes here..
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About this application.
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose language.
        /// </summary>
        public static string SettingsPageChooseLanguageText {
            get {
                return ResourceManager.GetString("SettingsPageChooseLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose Theme.
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Personalization.
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Privacy Statement.
        /// </summary>
        public static string SettingsPagePrivacyStatementText {
            get {
                return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dark.
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Light.
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default.
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go back.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Project tree.
        /// </summary>
        public static string ShellPagePaneTabItemProjectHeader {
            get {
                return ResourceManager.GetString("ShellPagePaneTabItemProjectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string ShellPageRibbonBackstageTabSettingsHeader {
            get {
                return ResourceManager.GetString("ShellPageRibbonBackstageTabSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editing language.
        /// </summary>
        public static string ShellPageRibbonHomeEditingLanguageTitle {
            get {
                return ResourceManager.GetString("ShellPageRibbonHomeEditingLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open.
        /// </summary>
        public static string ShellPageRibbonHomeOpenButtonText {
            get {
                return ResourceManager.GetString("ShellPageRibbonHomeOpenButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Project languages.
        /// </summary>
        public static string ShellPageRibbonHomeProjectLanguagesGroupHeader {
            get {
                return ResourceManager.GetString("ShellPageRibbonHomeProjectLanguagesGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reference language.
        /// </summary>
        public static string ShellPageRibbonHomeReferenceLanguageTitle {
            get {
                return ResourceManager.GetString("ShellPageRibbonHomeReferenceLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string ShellPageRibbonHomeSaveButtonText {
            get {
                return ResourceManager.GetString("ShellPageRibbonHomeSaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Build alarms.
        /// </summary>
        public static string ShellPageRibbonTabConnexionBuildAlarmsHeader {
            get {
                return ResourceManager.GetString("ShellPageRibbonTabConnexionBuildAlarmsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Build tags.
        /// </summary>
        public static string ShellPageRibbonTabConnexionBuildTagsHeader {
            get {
                return ResourceManager.GetString("ShellPageRibbonTabConnexionBuildTagsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexions.
        /// </summary>
        public static string ShellPageRibbonTabConnexionHeader {
            get {
                return ResourceManager.GetString("ShellPageRibbonTabConnexionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        public static string ShellPageRibbonTabHomeHeader {
            get {
                return ResourceManager.GetString("ShellPageRibbonTabHomeHeader", resourceCulture);
            }
        }
    }
}
